version: '2.4'
services:
  timeseries_forecasting_master:
    container_name: timeseries_forecasting_master
    build: .
    image: timeseries_forecasting:torch-cuda
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
#      - ./web.env
#    command: nvidia-smi
    tty: true
    command: /bin/bash
    volumes:
      - .:/src
    ports:
      - "8008:8008"
      - "6006:6006"
      - "6007:6007"